# ABOUTME: Cloud Build configuration for deploying to Cloud Run.
# ABOUTME: Reads Firebase config from Secret Manager and passes to Docker build.

steps:
  # Build and push using cloud-sdk (which has both gcloud and docker)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -ex

        # Fetch secret
        gcloud secrets versions access latest --secret=firebase-web-config --project=$PROJECT_ID > /tmp/config.env
        echo "=== Config fetched ==="
        cat /tmp/config.env

        # Parse values
        API_KEY=$(grep NEXT_PUBLIC_FIREBASE_API_KEY /tmp/config.env | cut -d'=' -f2)
        AUTH_DOMAIN=$(grep NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN /tmp/config.env | cut -d'=' -f2)
        FB_PROJECT_ID=$(grep NEXT_PUBLIC_FIREBASE_PROJECT_ID /tmp/config.env | cut -d'=' -f2)
        STORAGE_BUCKET=$(grep NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET /tmp/config.env | cut -d'=' -f2)
        MESSAGING_ID=$(grep NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID /tmp/config.env | cut -d'=' -f2)
        APP_ID=$(grep NEXT_PUBLIC_FIREBASE_APP_ID /tmp/config.env | cut -d'=' -f2)

        echo "API_KEY=$$API_KEY"
        echo "AUTH_DOMAIN=$$AUTH_DOMAIN"

        # Build Docker image
        docker build \
          --build-arg "NEXT_PUBLIC_FIREBASE_API_KEY=$$API_KEY" \
          --build-arg "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$$AUTH_DOMAIN" \
          --build-arg "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$$FB_PROJECT_ID" \
          --build-arg "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$$STORAGE_BUCKET" \
          --build-arg "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$$MESSAGING_ID" \
          --build-arg "NEXT_PUBLIC_FIREBASE_APP_ID=$$APP_ID" \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:latest \
          .

        # Push images
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:latest

        # Deploy to Cloud Run
        gcloud run deploy journal-app \
          --image us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA \
          --region us-central1 \
          --allow-unauthenticated

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
