# ABOUTME: Cloud Build configuration for deploying to Cloud Run.
# ABOUTME: Reads Firebase config from Secret Manager and passes to Docker build.

steps:
  # Step 1: Fetch and parse secret, write individual files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud secrets versions access latest --secret=firebase-web-config --project=$PROJECT_ID > /workspace/config.env

        # Write each value to a separate file (no newlines, no escaping issues)
        grep NEXT_PUBLIC_FIREBASE_API_KEY /workspace/config.env | cut -d'=' -f2 > /workspace/API_KEY
        grep NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN /workspace/config.env | cut -d'=' -f2 > /workspace/AUTH_DOMAIN
        grep NEXT_PUBLIC_FIREBASE_PROJECT_ID /workspace/config.env | cut -d'=' -f2 > /workspace/FB_PROJECT_ID
        grep NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET /workspace/config.env | cut -d'=' -f2 > /workspace/STORAGE_BUCKET
        grep NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID /workspace/config.env | cut -d'=' -f2 > /workspace/MESSAGING_ID
        grep NEXT_PUBLIC_FIREBASE_APP_ID /workspace/config.env | cut -d'=' -f2 > /workspace/APP_ID

        echo "Files created:"
        cat /workspace/API_KEY

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg "NEXT_PUBLIC_FIREBASE_API_KEY=$(cat /workspace/API_KEY)" \
          --build-arg "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$(cat /workspace/AUTH_DOMAIN)" \
          --build-arg "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$(cat /workspace/FB_PROJECT_ID)" \
          --build-arg "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$(cat /workspace/STORAGE_BUCKET)" \
          --build-arg "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$(cat /workspace/MESSAGING_ID)" \
          --build-arg "NEXT_PUBLIC_FIREBASE_APP_ID=$(cat /workspace/APP_ID)" \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:latest \
          .

  # Step 3: Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:latest']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'journal-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/journal-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
